--[[ iSAC - Custom Values List 

	These are lists of default values to be used with iSAC. These values can be used, but you're not limited to and can specify your own values if you wish to do so.
	Many, if not all, of these values are taken from Sida's Auto Carry.
	
	]]--

return {
	ResetSpells = {
		Blitzcrank = "PowerFist",
		Darius = "DariusNoxianTacticsONH",
		Nidalee = "Takedown",
		Sivir = "Ricochet",
		Teemo = "BlindingDart",
		Vayne = "VayneTumble",
		Jax = "JaxEmpowerTwo",
		Mordekaiser = "MordekaiserMaceOfSpades",
		Nasus = "SiphoningStrikeNew",
		Rengar = "RengarQ",
		Wukong = "MonkeyKingDoubleAttack",
		Yorick = "YorickSpectral",
		Vi = "ViE",
		Garen = "GarenSlash3",
		Hecarim = "HecarimRamp",
		XinZhao = "XenZhaoComboTarget",
		Leona = "LeonaShieldOfDaybreak",
		Shyvana = {"ShyvanaDoubleAttack", "shyvanadoubleattackdragon"},
		Talon = "TalonNoxianDiplomacy",
		Trundle = "TrundleTrollSmash",
		Volibear = "VolibearQ",
		Poppy = "PoppyDevastatingBlow",
	},
	AASpells = {
		Ashe = "frostarrow",
		Caitlyn = "CaitlynHeadshotMissile",
		Quinn = "QuinnWEnhanced",
		Trundle = "TrundleQ",
		XinZhao = "XenZhaoThrust",
		Garen = "GarenSlash2",
		Renekton = {"RenektonExecute", "RenektonSuperExecute"},
	},
	projSpeeds = {
		Ahri         = { projSpeed = 1.6},
		Anivia       = { projSpeed = 1.05},
		Annie        = { projSpeed = 1.0},
		Ashe         = { projSpeed = 2.0},
		Brand        = { projSpeed = 1.975},
		Caitlyn      = { projSpeed = 2.5},
		Cassiopeia   = { projSpeed = 1.22},
		Corki        = { projSpeed = 2.0},
		Draven       = { projSpeed = 1.4},
		Ezreal       = { projSpeed = 2.0},
		FiddleSticks = { projSpeed = 1.75},
		Graves       = { projSpeed = 3.0},
		Heimerdinger = { projSpeed = 1.4},
		Janna        = { projSpeed = 1.2},
		Jayce        = { projSpeed = 2.2},
		Karma        = { projSpeed = 1.2},
		Karthus      = { projSpeed = 1.25},
		Kayle        = { projSpeed = 1.8},
		Kennen       = { projSpeed = 1.35},
		KogMaw       = { projSpeed = 1.8},
		Leblanc      = { projSpeed = 1.7},
		Lulu         = { projSpeed = 2.5},
		Lux          = { projSpeed = 1.55},
		Malzahar     = { projSpeed = 1.5},
		MissFortune  = { projSpeed = 2.0},
		Morgana      = { projSpeed = 1.6},
		Nidalee      = { projSpeed = 1.7},
		Orianna      = { projSpeed = 1.4},
		Quinn        = { projSpeed = 1.85},
		Ryze         = { projSpeed = 2.4},
		Sivir        = { projSpeed = 1.4},
		Sona         = { projSpeed = 1.6},
		Soraka       = { projSpeed = 1.0},
		Swain        = { projSpeed = 1.6},
		Syndra       = { projSpeed = 1.2},
		Teemo        = { projSpeed = 1.3},
		Tristana     = { projSpeed = 2.25},
		TwistedFate  = { projSpeed = 1.5},
		Twitch       = { projSpeed = 2.5},
		Urgot        = { projSpeed = 1.3},
		Vayne        = { projSpeed = 2.0},
		Varus        = { projSpeed = 2.0},
		Veigar       = { projSpeed = 1.05},
		Viktor       = { projSpeed = 2.25},
		Vladimir     = { projSpeed = 1.4},
		Xerath       = { projSpeed = 1.2},
		Ziggs        = { projSpeed = 1.5},
		Zilean       = { projSpeed = 1.25},
		Zyra         = { projSpeed = 1.7},
	},
}